name       : openscenegraph
version    : 3.4.0
release    : 11
source     :
    - https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.4.0.tar.gz : 0d5efe12b923130d14a6fce5866675d7625fcfb1c004c9f9b10034b9feb61ac2
license    : LGPL-2.0
component  : programming
summary    : The OpenSceneGraph is an open source high performance 3D graphics toolkit
description: |
    The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(gstreamer-0.10)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(jasper)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
    - pkgconfig(xrandr)
    - pkgconfig(zlib)
    - giflib-devel
setup      : |
    %patch -p2 < $pkgfiles/openscenegraph-ffmpeg3.patch
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
