name       : openscenegraph
version    : 3.5.5
release    : 6
source     :
    - https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.5.5.tar.gz : f44c96ade3a1d3c547f36504d75633bedbb9b8f6f42dac4fff75166db7d3aadf
license    : LGPL-2.0
component  : programming
summary    : The OpenSceneGraph is an open source high performance 3D graphics toolkit
description: |
    The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(gstreamer-0.10)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
    - pkgconfig(xrandr)
    - pkgconfig(zlib)
    - giflib-devel
    - jasper-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
