name       : openscenegraph
version    : 3.4.1
release    : 19
source     :
    - https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.4.1.tar.gz : 930eb46f05781a76883ec16c5f49cfb29a059421db131005d75bec4d78401fd5
license    : LGPL-2.0-or-later
component  : programming
summary    : The OpenSceneGraph is an open source high performance 3D graphics toolkit
description: |
    The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(jasper)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libvncserver)
    - pkgconfig(lua)
    - pkgconfig(poppler-glib)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
    - pkgconfig(xrandr)
    - giflib-devel
setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DOSG_USE_LOCAL_LUA_SOURCE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
