name       : openscenegraph
version    : 3.6.5
release    : 28
source     :
    - https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.6.5.tar.gz : aea196550f02974d6d09291c5d83b51ca6a03b3767e234a8c0e21322927d1e12
license    : LGPL-2.1-only WITH WxWindows-exception-3.1
component  : programming.library
homepage   : http://www.openscenegraph.org/
summary    : The OpenSceneGraph is an open source high performance 3D graphics toolkit
description: |
    The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling.
builddeps  :
    - pkgconfig(collada-dom)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - giflib-devel
setup      : |
    %apply_patches
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DOSG_USE_LOCAL_LUA_SOURCE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
